 $('#errorMsg').hide();
 $('#errorMsg').hide();
$('#loader').hide();
$('#successMsg').hide();
$(document).ready(function () {
    $('#ps').hide();

    $("#sbtn").click(function(e){
        e.preventDefault();

        alert("ss");
        var username = $("#student-username").val();
        var pass = $("#student-password").val();

        $.ajax({
            url: "../repository/lecturerRepository.php",
            type: "POST",
            data: {
                type:'studentlogin',
            },
            success: function(data){
                
alert(data);

            },
            error: function(error){
                alert(error);
            }
        });


    });
 
  var myCheckbox = document.getElementById('resetPassword');

 
  myCheckbox.addEventListener('change', function() {
    
      if (myCheckbox.checked) {
        $('#ps').show();

        $('#pass').val('lec'+ $('#lcode').val());
        $('#repass').val('lec'+ $('#lcode').val());
      } else {
        $('#ps').hide();
        $('#pass').val('');
        $('#repass').val('');
      }
  });
   
    function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
    }
    
    // Get the id from the URL
    var id = getParameterByName('id');
    
    //get data
    $.ajax({
        url: "../repository/lecturerRepository.php",
        type: "GET",
        data: { type: 'getDataById',
    id:id},
        success: function(data){
       


          var jsonData = JSON.parse(data);

          jsonData.forEach(function (lecturer, index) {

            
            var fullName = lecturer.name;

            var nameParts = fullName.split(' ');
            
            
            var firstName = nameParts[0];
            var lastName = nameParts.slice(1).join(' ');
            $('#fname').val(firstName);
            $('#lname').val(lastName);
            $('#lcode').val(lecturer.lec_code);
            $('#category').val(lecturer.course);
            

          });

      
            
        }
    });






       // Toggle password visibility
       $('#togglePassword').click(function () {
        var passwordInput = $('#pass');
        var toggleIcon = $('#togglePasswordIcon');

        if (passwordInput.attr('type') === 'password') {
            passwordInput.attr('type', 'text');
            toggleIcon.removeClass('fa-eye').addClass('fa-eye-slash');
        } else {
            passwordInput.attr('type', 'password');
            toggleIcon.removeClass('fa-eye-slash').addClass('fa-eye');
        }
    });

    $('#fname, #lname').on('input', function () {
       
        var firstName = $('#fname').val().toLowerCase();
        var lastName = $('#lname').val().toLowerCase();
        
        var lecturerCode = (firstName + lastName.substring(0, 2)).toLowerCase() + '@lecnibm';

      
        $('#lcode').val(lecturerCode);
        function generatePassword(lecturerCode) {
            return 'lec' + lecturerCode;
        }
        
     
        $('#category').change(function () {
            if ($(this).val() !== '') {
                $(this).removeClass('border-danger');
                $('#errorMsg').hide();
            }
        });
        
        var autoGeneratedPassword = generatePassword(lecturerCode);
            $('#pass').val(autoGeneratedPassword);

        var autoGeneratedPassword = generatePassword(lecturerCode);
            $('#repass').val(autoGeneratedPassword);

            $('#submit').off('click').on('click', function (e) {
                e.preventDefault();
            
                var firstName = $('#fname').val().trim();
                var lastName = $('#lname').val().trim();
                var lecturerCode = $('#lcode').val();
                var category = $('#category').val();
                var password = $('#pass').val();
                var rePassword = $('#repass').val();
            
                $('#errorMsg').hide();
                $('.form-control').removeClass('border-danger');
            
                if (firstName === '' || lastName === '') {
                    $('#errorMsg').text('First name and last name should not be empty.').show();
                    return false;
                }
            
                if (/\s/.test(firstName) || /\s/.test(lastName)) {
                    $('#errorMsg').text('First name and last name should not contain spaces.').show();
                    return false;
                }
            
                if (category === '') {
                    $('#category').addClass('border-danger');
                    $('#errorMsg').text('Please select the course.').show();
                    return false;
                }
            
               
            if(password != ''){
                if (!password.includes('lec') || !password.includes(lecturerCode)) {
                    $('#errorMsg').text('Auto-generated password should contain "lec" and the lecturer code.').show();
                    $('#pass').addClass('border-danger');
                    return false;
                }
            
                if (password !== rePassword) {
                    $('#errorMsg').text('Passwords do not match.').show();
                    $('#repass').addClass('border-danger');
                    return false;
                }
            }

                var myCheckbox = document.getElementById('resetPassword');

                if (myCheckbox.checked) {
        
                  } else {
                    
                    $('#pass').val('');
                    $('#repass').val('');
                  }
            
                $('#errorMsg').text('');
                $("#card").hide();
                $("#loader").show();  
        
        var name = $('#fname').val() + " " + $('#lname').val();
        var lecCode = $('#lcode').val(); 
        var course = $('#category').val();
        var lecPass = $('#pass').val();
        var id = getParameterByName('id');
      
                            $.ajax({
                                url: "../repository/lecturerRepository.php",
                                type: "POST",
                                data: {
                                    type:'update',
                                    name:name,
                                    lecCode:lecCode,
                                    course:course,
                                    lecPass:lecPass,
                                id:id},
                                success: function(data){
                                    
                                    setTimeout(function () {
                                        $("#loader").fadeOut(500, function () {
                                            $("#card").fadeIn(500);
                                        });
                                    }, 500);

                
                                    if(data == 0){
                                        $('#successMsg').fadeIn(500, function () {
                                            // Hide success message after 500ms
                                            setTimeout(function () {
                                                $('#successMsg').fadeOut(500);
                                            }, 5000);
                                        });
                
                                         // Perform other actions if validation is successful
                downloadTextFile(firstName + '_' + lastName + 'Lect_details.txt', 'Lecturer Code: ' + lecturerCode + '\nPassword: ' + password);
                setTimeout(function() {
                    window.location.href = 'lecturer.html';
                }, 3000);
                                    }else{
                                        $('#errorMsg').html('Something Went Wrong!');
                                        $('#errorMsg').fadeIn(500, function () {
                                            // Hide success message after 500ms
                                            setTimeout(function () {
                                                $('#errorMsg').fadeOut(500);
                                            }, 5000);
                                        });
                                    }
                
                
                                },
                                error: function(error){
                                    alert(error);
                                }
                            });
    
            
                return true;
            });
            
            
            
            function downloadTextFile(filename, text) {
                var blob = new Blob([text], { type: 'text/plain' });
                var a = document.createElement('a');
                a.href = URL.createObjectURL(blob);
                a.download = filename;
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
            }

            $('#clear').click(function () {
                $('#errorMsg').hide();
                $('.form-control').removeClass('border-danger');
                $('form')[0].reset();  // Reset the form fields
            });

        $('#back').click(function () {
            // Implement your back button logic here
        });

    });
});